const BASE_URL = process.env.BASE_URL || "http://localhost:3002";

const recipes = [
    {
        name: "Spaghetti Carbonara",
        description: "Classic Italian pasta dish with eggs, cheese, pancetta, and pepper.",
        instructions: "Cook spaghetti, mix with cooked pancetta, eggs, and cheese.",
        prepTime: 10,
        cookTime: 20,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/spaghetti_carbonara.jpg`,
        userId: 1,
    },
    {
        name: "Margherita Pizza",
        description: "Traditional Italian pizza with tomatoes, sliced mozzarella, basil, and extra-virgin olive oil.",
        instructions: "Prepare dough, add toppings, and bake in oven.",
        prepTime: 30,
        cookTime: 20,
        servings: 2,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/margherita_pizza.jpg`,
        userId: 1,
    },
    {
        name: "Classic Cheeseburger",
        description: "Grilled beef patty with cheese, lettuce, tomato, and onion on a bun.",
        instructions: "Grill beef patty, melt cheese on top, assemble the burger with toppings.",
        prepTime: 15,
        cookTime: 10,
        servings: 1,
        category: "Main",
        season: "Summer",
        imageURL: `${BASE_URL}/images/cheeseburger.jpg`,
        userId: 1,
    },
    {
        name: "Chicken Alfredo",
        description: "Creamy pasta with chicken and Parmesan cheese",
        instructions: "Cook pasta, sauté chicken, mix with Alfredo sauce, and garnish with parsley.",
        prepTime: 15,
        cookTime: 30,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/chicken_alfredo.jpg`,
        userId: 1,
    },
    {
        name: "Beef Stew",
        description: "Hearty stew made with beef, potatoes, and carrots",
        instructions: "Brown beef, add vegetables and broth, and simmer until tender.",
        prepTime: 20,
        cookTime: 120,
        servings: 6,
        category: "Main",
        season: "Winter",
        imageURL: `${BASE_URL}/images/beef_stew.jpg`,
        userId: 1,
    },
    {
        name: "Pasta",
        description: "Pasta with tomato sauce",
        instructions: "Cook the pasta, add the tomato sauce",
        prepTime: 10,
        cookTime: 20,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/pasta.jpg`,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 1,
    },
    {
        name: "Grilled Cheese Sandwich",
        description: "A quick and classic grilled cheese sandwich",
        instructions: "Place cheese between slices of bread and grill until golden brown",
        prepTime: 5,
        cookTime: 10,
        servings: 1,
        category: "Snack",
        season: "All",
        imageURL: `${BASE_URL}/images/grilled_cheese.jpg`,
        createdAt: new Date(),
        updatedAt: new Date(),
        userId: 1,
    },
    {
        name: "Chicken Tikka Masala",
        description: "Indian curry dish with marinated chicken pieces in a creamy tomato sauce.",
        instructions: "Marinate and grill chicken, prepare sauce with tomatoes, cream, and spices.",
        prepTime: 20,
        cookTime: 40,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/chicken_tikka_masala.jpg`,
        userId: 1,
    },
    {
        name: "Fish Tacos",
        description: "Tacos filled with grilled or fried fish, topped with a zesty slaw and creamy sauce.",
        instructions: "Prepare fish, assemble tacos with toppings and sauces.",
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        category: "Main",
        season: "Summer",
        imageURL: `${BASE_URL}/images/fish_tacos.jpg`,
        userId: 1,
    },
    {
        name: "Ratatouille",
        description: "French vegetable stew made with zucchini, eggplant, peppers, and tomato.",
        instructions: "Slice vegetables, layer in a dish, and bake.",
        prepTime: 30,
        cookTime: 60,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/ratatouille.jpg`,
        userId: 1,
    },
    {
        name: "Pad Thai",
        description: "Thai stir-fried noodles with eggs, fish sauce, tamarind juice, red chili pepper, plus bean sprouts, chicken, shrimp, or tofu.",
        instructions: "Stir-fry noodles with proteins and sauces, serve with lime wedges.",
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/pad_thai.jpg`,
        userId: 1,
    },
    {
        name: "Butternut Squash Soup",
        description: "Creamy soup made from roasted butternut squash, onions, and herbs.",
        instructions: "Roast squash, blend with sautéed onions and broth.",
        prepTime: 15,
        cookTime: 45,
        servings: 4,
        category: "Soup",
        season: "Fall",
        imageURL: `${BASE_URL}/images/butternut_squash_soup.jpg`,
        userId: 1,
    },
    {
        name: "Caesar Salad",
        description: "Classic salad with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing.",
        instructions: "Toss lettuce with croutons, cheese, and dressing.",
        prepTime: 10,
        cookTime: 0,
        servings: 2,
        category: "Salad",
        season: "All",
        imageURL: `${BASE_URL}/images/caesar_salad.jpg`,
        userId: 1,
    },
    {
        name: "Mushroom Risotto",
        description: "Creamy Italian rice dish cooked with broth and flavored with mushrooms, onions, garlic, and Parmesan cheese.",
        instructions: "Cook risotto rice with broth, add sautéed mushrooms and cheese.",
        prepTime: 10,
        cookTime: 30,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/mushroom_risotto.jpg`,
        userId: 1,
    },
    {
        name: "Beef Bourguignon",
        description: "French beef stew braised in red wine, often with mushrooms, onions, and bacon.",
        instructions: "Brown beef, simmer with wine and vegetables.",
        prepTime: 20,
        cookTime: 180,
        servings: 6,
        category: "Main",
        season: "Winter",
        imageURL: `${BASE_URL}/images/beef_bourguignon.jpg`,
        userId: 1,
    },
    {
        name: "Chicken Caesar Wrap",
        description: "Grilled chicken with Caesar salad wrapped in a flour tortilla.",
        instructions: "Grill chicken, combine with salad, wrap in tortilla.",
        prepTime: 10,
        cookTime: 10,
        servings: 2,
        category: "Snack",
        season: "All",
        imageURL: `${BASE_URL}/images/chicken_caesar_wrap.jpg`,
        userId: 1,
    },
    {
        name: "Banana Bread",
        description: "Sweet bread made with mashed bananas.",
        instructions: "Combine ingredients and bake in a loaf pan.",
        prepTime: 15,
        cookTime: 60,
        servings: 8,
        category: "Dessert",
        season: "All",
        imageURL: `${BASE_URL}/images/banana_bread.jpg`,
        userId: 1,
    },
    {
        name: "Caprese Salad",
        description: "Fresh salad with tomatoes, mozzarella cheese, basil, and balsamic glaze.",
        instructions: "Slice tomatoes and mozzarella, arrange with basil, and drizzle with balsamic glaze.",
        prepTime: 10,
        cookTime: 0,
        servings: 2,
        category: "Salad",
        season: "Summer",
        imageURL: `${BASE_URL}/images/caprese_salad.jpg`,
        userId: 1,
    },
    {
        name: "Shrimp Scampi Pasta",
        description: "Garlic-infused shrimp served over a bed of linguine pasta.",
        instructions: "Sauté shrimp in garlic butter, toss with linguine, and garnish with parsley.",
        prepTime: 15,
        cookTime: 20,
        servings: 3,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/shrimp_scampi_pasta.jpg`,
        userId: 1,
    },
    {
        name: "Vegetable Curry",
        description: "Spicy curry with a variety of vegetables and aromatic spices.",
        instructions: "Sauté vegetables, add curry spices, and simmer until tender.",
        prepTime: 20,
        cookTime: 25,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/vegetable_curry.jpg`,
        userId: 1,
    },
    {
        name: "Lemon Garlic Butter Salmon",
        description: "Baked or grilled salmon fillets with a flavorful lemon garlic butter sauce.",
        instructions: "Season salmon, bake or grill, and drizzle with lemon garlic butter sauce.",
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/lemon_garlic_butter_salmon.jpg`,
        userId: 1,
    },
    {
        name: "Chocolate Chip Cookies",
        description: "Classic homemade cookies with chocolate chips.",
        instructions: "Mix ingredients, form into cookies, and bake until golden brown.",
        prepTime: 15,
        cookTime: 12,
        servings: 12,
        category: "Dessert",
        season: "All",
        imageURL: `${BASE_URL}/images/chocolate_chip_cookies.jpg`,
        userId: 1,
    },
    {
        name: "Chicken Parmesan",
        description: "Breaded and baked chicken cutlets topped with marinara sauce and melted mozzarella.",
        instructions: "Bread and bake chicken, top with marinara and mozzarella, and bake until bubbly.",
        prepTime: 20,
        cookTime: 25,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/chicken_parmesan.jpg`,
        userId: 1,
    },
    {
        name: "Vegetarian Tacos",
        description: "Tacos filled with seasoned black beans, corn, avocado, and salsa.",
        instructions: "Combine black beans, corn, and toppings in taco shells.",
        prepTime: 15,
        cookTime: 10,
        servings: 3,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/vegetarian_tacos.jpg`,
        userId: 1,
    },
    {
        name: "Pesto Pasta with Cherry Tomatoes",
        description: "Pasta tossed in a basil pesto sauce with halved cherry tomatoes.",
        instructions: "Cook pasta, mix with pesto, and add cherry tomatoes.",
        prepTime: 15,
        cookTime: 15,
        servings: 2,
        category: "Main",
        season: "Summer",
        imageURL: `${BASE_URL}/images/pesto_pasta_cherry_tomatoes.jpg`,
        userId: 1,
    },
    {
        name: "Hawaiian Chicken Skewers",
        description: "Grilled chicken skewers with pineapple chunks and bell peppers.",
        instructions: "Marinate and grill chicken with pineapple and bell peppers.",
        prepTime: 20,
        cookTime: 15,
        servings: 4,
        category: "Main",
        season: "Summer",
        imageURL: `${BASE_URL}/images/hawaiian_chicken_skewers.jpg`,
        userId: 1,
    },
    {
        name: "Tomato Basil Bruschetta",
        description: "Toasted bread topped with diced tomatoes, fresh basil, garlic, and balsamic glaze.",
        instructions: "Combine diced tomatoes, basil, and garlic, spoon onto toasted bread, and drizzle with balsamic glaze.",
        prepTime: 15,
        cookTime: 5,
        servings: 3,
        category: "Appetizer",
        season: "Summer",
        imageURL: `${BASE_URL}/images/tomato_basil_bruschetta.jpg`,
        userId: 1,
    },
    {
        name: "Chicken Quesadillas",
        description: "Grilled tortillas filled with seasoned chicken, cheese, and sautéed peppers and onions.",
        instructions: "Grill chicken, sauté peppers and onions, assemble quesadillas, and cook until cheese is melted.",
        prepTime: 15,
        cookTime: 15,
        servings: 3,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/chicken_quesadillas.jpg`,
        userId: 1,
    },
    {
        name: "Vegetable Stir-Fry",
        description: "Assorted vegetables stir-fried in a savory soy and ginger sauce.",
        instructions: "Sauté vegetables in soy and ginger sauce until crisp-tender.",
        prepTime: 10,
        cookTime: 15,
        servings: 4,
        category: "Main",
        season: "All",
        imageURL: `${BASE_URL}/images/vegetable_stir_fry.jpg`,
        userId: 1,
    },
    {
        name: "Caprese Panini",
        description: "Pressed sandwich with mozzarella, tomatoes, fresh basil, and balsamic glaze.",
        instructions: "Layer mozzarella, tomatoes, and basil on bread, press in a panini maker until golden, and drizzle with balsamic glaze.",
        prepTime: 10,
        cookTime: 5,
        servings: 2,
        category: "Main",
        season: "Summer",
        imageURL: `${BASE_URL}/images/caprese_panini.jpg`,
        userId: 1,
    }

];

module.exports = recipes;